# что представляет собой мой dbt-проект и что с ним делать.

name: analytics
version: '1.0.0'
config-version: 2

profile: analytics

model-paths: ["models"]

models:
  analytics:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: analytics